In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
np.array([3.14,5,6,7,8])

array([3.14, 5.  , 6.  , 7.  , 8.  ])

In [5]:
a = np.array([[1,2,3],
              [2,3,4]])


In [6]:
a.shape

(2, 3)

In [7]:
a.ndim

2

In [8]:
a.dtype

dtype('int32')

Creating Numpy array from scratch

In [9]:
np.zeros([2,4], dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [10]:
np.ones((4,5) ,dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.full((3,4) ,6.9)

array([[6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9]])

In [13]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
np.random.random((3,3))

array([[0.90376439, 0.38880173, 0.05234229],
       [0.54167291, 0.8517068 , 0.85363225],
       [0.20247612, 0.86956552, 0.53160242]])

In [15]:
np.random.seed(0)
np.random.random((3,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492]])

In [16]:
np.random.normal(0,2,(3,4))

array([[ 1.52207545,  0.24335003,  0.88772647,  0.66734865],
       [ 2.98815815, -0.41031653,  0.6261354 , -1.70819148],
       [-5.10597963,  1.30723719,  1.7288724 , -1.48433004]])

In [17]:
np.random.randint(0,5 ,(3,3))

array([[4, 2, 0],
       [0, 4, 0],
       [4, 1, 4]])

In [18]:
x1 = np.random.randint(20, size = 6)
print(x1)

[ 9 10  1  1  7  9]


In [19]:
x1[4] , x1[0] , x1[-1]

(7, 9, 9)

multi dimensinal array

In [20]:
x2 = np.random.randint(10, size = (3,4))
print(x2)

[[9 3 6 7]
 [2 0 3 5]
 [9 4 4 6]]


In [21]:
x2[1,2] , x2[2,2], x2[-1,-1]

(3, 4, 6)

In [22]:
x2[1,2] = 6
print(x2)

[[9 3 6 7]
 [2 0 6 5]
 [9 4 4 6]]


slicing 

In [23]:
x1

array([ 9, 10,  1,  1,  7,  9])

In [24]:
x1[0:3]

array([ 9, 10,  1])

In [25]:
x1[::2]

array([9, 1, 7])

In [26]:
x2

array([[9, 3, 6, 7],
       [2, 0, 6, 5],
       [9, 4, 4, 6]])

In [27]:
x2[:2,:3]

array([[9, 3, 6],
       [2, 0, 6]])

reshaping of Arrays & transpose

In [28]:
grid = np.arange(1,10)
grid.shape

(9,)

In [29]:
grid.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
x = np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [31]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

Array concatenation and splitting 

In [32]:
x= np.array([1,2,3])
y= np.array([3,2,1])


In [33]:
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [34]:
grid = np.array([[1,2,3] ,[4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
np.concatenate((grid,grid)) # axis -0 by default 

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [36]:
np.concatenate((grid,grid) ,axis= 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [37]:
x= np.array([1,2,3])
grid = np.array([[9,8,7],[6,5,4]])


In [38]:
np.vstack((x,grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [39]:
# horizontally stack the arrays: hstack
y = np.array([[99],[99]])

np.hstack((y,grid))

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

splitting of arrays

In [40]:
x = np.array([1,4,77,55,33,1,34,2])
x1,x2,x3 =np.split(x,[3,5])


In [41]:
x1

array([ 1,  4, 77])

In [42]:
x2

array([55, 33])

In [43]:
x3

array([ 1, 34,  2])

In [44]:
a = np.arange(3)
print(a)

[0 1 2]


In [45]:
a + 5

array([5, 6, 7])

In [46]:
b = np.ones((3,3))
b1 = b*5
b2 = b+5
print(b1)
print()
print(b2)


[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]

[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]


In [47]:
c = np.arange(3).reshape((3,1))
c

array([[0],
       [1],
       [2]])

In [48]:
a+c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

manipulating & comparing arrays


In [49]:
list_number = [1,2,3]
ll = np.array(list_number)
ll

array([1, 2, 3])

In [50]:
sum(ll)

6

In [51]:
massive_array = np.random.random(10000)
massive_array[:5]
massive_array.size
massive_array.shape

(10000,)

In [52]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

747 µs ± 2.59 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
5.08 µs ± 50.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [53]:
np.mean(massive_array)

0.4962511866026875

In [55]:
max= np.max(massive_array)
min= np.min(massive_array)
print("max: ",max)
print("min: ",min)


max:  0.9999779517807228
min:  7.2449638492178e-05


statistics 
standard deviation and variance

In [56]:
dog_height = [600,470,170,430,300]
dog_height = np.array(dog_height)


In [57]:
# do lech chuan
np.std(dog_height)

147.32277488562318

In [58]:
# phuong sai 
np.var(dog_height)

21704.0

In [59]:
# do lech chuan cach lam khac
np.sqrt(np.var(dog_height))

147.32277488562318

sorting arrrays 

In [62]:
x = np.array([2,1,9,14,3,5,7])
np.sort(x)

array([ 1,  2,  3,  5,  7,  9, 14])

In [63]:
matA = np.random.randint(1,10, size=(4,6))
matA 

array([[9, 7, 3, 7, 1, 2],
       [2, 1, 6, 3, 7, 1],
       [4, 7, 7, 3, 6, 8],
       [4, 2, 1, 2, 1, 6]])

In [65]:
np.sort(matA )
# sap xep theo cot
np.sort(matA , axis=0)

array([[2, 1, 1, 2, 1, 1],
       [4, 2, 3, 3, 1, 2],
       [4, 7, 6, 3, 6, 6],
       [9, 7, 7, 7, 7, 8]])

In [66]:
# sap xep theo hang
np.sort(matA, axis=1)

array([[1, 2, 3, 7, 7, 9],
       [1, 1, 2, 3, 6, 7],
       [3, 4, 6, 7, 7, 8],
       [1, 1, 2, 2, 4, 6]])

liner algebra

In [69]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

B = np.array([[11,12],
              [14,15],
              [17,18]])
# A(3X3) , B(3X2)

In [71]:
#TICH VO HUONG 
A.dot(B)
# 1*11 + 2*14 +3*17 = 90 , tuong tu nhu cai khac

array([[ 90,  96],
       [216, 231],
       [342, 366]])

In [73]:
B.T

array([[11, 14, 17],
       [12, 15, 18]])

In [76]:
# Tich vo huong ma lam cach khac
B.T @ A

array([[186, 228, 270],
       [198, 243, 288]])

In [80]:
np.random.seed(0) # seed de tao cac ma tran giong nhau
sales_amounts = np.random.randint(20, size= (5,3))

sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [84]:
import pandas as pd
weekly_sales = pd.DataFrame(sales_amounts , index= ["thu hai","thu ba","thu tu","thu nam","thu sau"], 
                                            columns=["almond butter","peanut butter","cashwew butter"])


In [85]:
weekly_sales

almond butter  peanut butter  cashwew butter
thu hai             12             15               0
thu ba               3              3               7
thu tu               9             19              18
thu nam              4              6              12
thu sau              1              6               7

In [86]:
gia = np.array([10,8,12])


In [87]:
butter_gia = pd.DataFrame(gia.reshape(1,3), index= ["Gia"], columns=["almond butter","peanut butter","cashwew butter"])

In [88]:
butter_gia

almond butter  peanut butter  cashwew butter
Gia             10              8              12

In [91]:
weekly_sales.shape, butter_gia.shape # (5,3) va (1,3) ko the nhan dc nen t phai dao chieu 
weekly_sales.shape, butter_gia.T.shape #(5,3) va (3,1)


((5, 3), (3, 1))

In [93]:
total_gia = weekly_sales.dot(butter_gia.T)
total_gia

Gia
thu hai  240
thu ba   138
thu tu   458
thu nam  232
thu sau  142

In [94]:
weekly_sales["Total gia"] = total_gia
weekly_sales

almond butter  peanut butter  cashwew butter  Total gia
thu hai             12             15               0        240
thu ba               3              3               7        138
thu tu               9             19              18        458
thu nam              4              6              12        232
thu sau              1              6               7        142